language: csharp
sudo: false
solution: SteamDatabaseBackend.sln
before_install:
  - cp ./settings.json.default ./settings.json
notifications:
  email: false
  irc:
    skip_join: false
    on_success: never
    on_failure: change
    channels:
      - "chat.freenode.net#steamdb"
    template:
      - "[%{repository_name}] %{message} - %{build_url}"
