language: csharp
solution: SteamDatabaseBackend.sln
before_install:
  - cp ./settings.json.default ./settings.json
notifications:
  email: false
  irc:
    skip_join: false
    on_success: never
    on_failure: always
    channels:
      - "chat.freenode.net#steamdb"
    template:
      - "%{repository}#%{build_number} (%{commit} by %{author}): %{message}"
      - "Build details: %{build_url}"
