sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.0.0

solution: SteamDatabaseBackend.sln

install:
  - cp ./settings.json.default ./settings.json
  - dotnet restore

script:
  - dotnet build

notifications:
  email: false
  irc:
    skip_join: false
    on_success: never
    on_failure: change
    channels:
      - "chat.freenode.net#steamdb"
    template:
      - "[%{repository_name}] %{message} - %{build_url}"
